=== ytchitaev/flat_to_xml_by_schema/schema.json
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "_name": {
      "type": "string",
      "description": "The name of the element."
    },
    "_type": {
      "type": "string",
      "enum": ["row", "header"],
      "description": "The type of the element specifying if it populates once (header) iterates over each dataset row (row)."
    },
    "_value": {
      "type": "string",
      "description": "The value associated with the element."
    },
    "_attributes": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "description": "The attributes associated with the element."
    },
    "_children": {
      "type": "array",
      "items": {
        "$ref": "#"
      },
      "description": "The child elements of the target element. Recurses to the root of the json schema."
    }
  },
  "required": ["_name", "_type"],
  "description": "Mandatory fields in root and recursive elements.",
  "additionalProperties": false
}

=== ytchitaev/flat_to_xml_by_schema/xml_definition.json
{
    "_name": "attributevalue1",
    "_type": "header",
    "_attributes": {
        "attributename2": "attributevalue2"
    },
    "_children": [
        {
            "_name": "attributename3",
            "_type": "header",
            "_children": [
                {
                    "_name": "attributename4",
                    "_type": "row",
                    "_attributes": {
                        "FK": "@Col1"
                    },
                    "_children": [
                        {
                            "_name": "attributename5",
                            "_type": "row",
                            "_children": [
                                {
                                    "_name": "attributechild1",
                                    "_type": "row",
                                    "_value": "@Col2"
                                },
                                {
                                    "_name": "attributechild2",
                                    "_type": "row",
                                    "_value": "@Col3"
                                },
                                {
                                    "_name": "attributechild3",
                                    "_type": "row",
                                    "_value": "@Col4"
                                },
                                {
                                    "_name": "attributechild4",
                                    "_type": "row",
                                    "_value": "@Col5"
                                },
                                {
                                    "_name": "attributechild5",
                                    "_type": "row",
                                    "_value": "@Col6"
                                },
                                {
                                    "_name": "attributechild6",
                                    "_type": "row",
                                    "_value": "@Col7"
                                },
                                {
                                    "_name": "attributechild7",
                                    "_type": "row",
                                    "_value": "@Col8"
                                },
                                {
                                    "_name": "attributechild8",
                                    "_type": "row",
                                    "_value": "@Col9"
                                }
                            ]
                        },
                        {
                            "_name": "attributename6",
                            "_type": "row",
                            "_children": [
                                {
                                    "_name": "attributename7",
                                    "_type": "row",
                                    "_attributes": {
                                        "Name": "@Col1"
                                    },
                                    "_value": "@Col2"
                                },
                                {
                                    "_name": "attributename8",
                                    "_type": "row",
                                    "_attributes": {
                                        "Name": "@Col3"
                                    },
                                    "_value": "@Col4"
                                },
                                {
                                    "_name": "attributename9",
                                    "_type": "row",
                                    "_attributes": {
                                        "Name": "@Col4"
                                    },
                                    "_value": "@Col10"
                                },
                                {
                                    "_name": "attributename10",
                                    "_type": "row",
                                    "_attributes": {
                                        "Name": "attributename11"
                                    },
                                    "_value": "@Col11"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
